version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pred_invest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  auth-server:
    container_name: auth-server
    build: ./PredInvestAuthServer
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - data-server
    environment:
    - CONFIG_PATH=./config/local.yaml

  data-server:
    build: ./PredInvestDataServer
    container_name:   data-server
    ports:
      - "5001:5001"
    depends_on:
      - postgres
  frontend:
    build: ./pred_invest_frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-server
      - data-server
      - postgres
  

volumes:
  pgdata: {}

