env: "local"
storage:
  user: "postgres"
  password: "postgres"
  dbname: "pred_invest"
  sslmode: "disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
#  user: "Shabby8574"